env:
  BOOTSNAP_PEDANTIC: '1'

up:
  - rust
  - ruby: 2.3.3
  - bundler
commands:
  build: bundle exec rake build
  test: 'bundle exec rake build && bundle exec bin/testunit'
  style: 'exec rubocop -D'
